"""Initial migration: workers, guests, attendance, face_encodings

Revision ID: b34f79dbe222
Revises: 
Create Date: 2026-07-19 18:50:10.117517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import TypeDecorator, CHAR
import uuid


# GUID Type for cross-database compatibility
class GUID(sa.TypeDecorator):
    """Platform-independent GUID type.
    Uses PostgreSQL's UUID type, otherwise uses CHAR(36) for SQLite.
    """
    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=True))
        else:
            return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "postgresql":
            return str(value)
        else:
            if isinstance(value, uuid.UUID):
                return str(value)
            return value

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "postgresql":
            return uuid.UUID(value)
        else:
            return uuid.UUID(value)


# revision identifiers, used by Alembic.
revision: str = 'b34f79dbe222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('guest_id', sa.String(length=20), nullable=False),
    sa.Column('encodings', sa.JSON(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('promoted', sa.Integer(), nullable=True),
    sa.Column('promoted_to_worker_id', GUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_guest_id'), 'guests', ['guest_id'], unique=True)
    op.create_index('ix_guests_promoted', 'guests', ['promoted'], unique=False)
    op.create_table('workers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_workers_active', 'workers', ['is_active'], unique=False)
    op.create_index('ix_workers_name', 'workers', ['name'], unique=False)
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=True)
    op.create_table('attendance_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('worker_id', GUID(), nullable=False),
    sa.Column('event_type', sa.Enum('in', 'out', name='event_type'), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('quality_score', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_event_date'), 'attendance_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_time'), 'attendance_events', ['event_time'], unique=False)
    op.create_index('ix_attendance_events_type', 'attendance_events', ['event_type'], unique=False)
    op.create_index('ix_attendance_events_worker_date', 'attendance_events', ['worker_id', 'event_date'], unique=False)
    op.create_table('face_encodings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('worker_id', GUID(), nullable=False),
    sa.Column('encoding', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_encodings_worker', 'face_encodings', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_face_encodings_worker', table_name='face_encodings')
    op.drop_table('face_encodings')
    op.drop_index('ix_attendance_events_worker_date', table_name='attendance_events')
    op.drop_index('ix_attendance_events_type', table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_time'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_date'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_index('ix_workers_name', table_name='workers')
    op.drop_index('ix_workers_active', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_guests_promoted', table_name='guests')
    op.drop_index(op.f('ix_guests_guest_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###